### ISSUE TITLE
need only one record support

### ISSUE THREAD

**Issue by kakas** [khiav223577/deep_pluck#17]
e.g.
```ruby
User.first.deep_pluck(:id, :name)

User.find(33).deep_pluck(:id, :name)
```

**Comment by khiav223577** [comment]
Just add support for deep_pluck to pluck at active model (https://github.com/khiav223577/deep_pluck/pull/19) and release it as [v1.1.0](
https://github.com/khiav223577/deep_pluck/releases/tag/v1.1.0)
