### ISSUE TITLE
Support for Mongoid

### ISSUE THREAD

**Issue by berniechiu** [khiav223577/deep_pluck#21]
Happy to see if we can support Mongoid in the future. Actually I can do it if I have some suggestions for the head start.

**Comment by khiav223577** [comment]
Hi, I'm welcome to seeing any contributes to this :)

Not sure how to read data from `Mongoid`. But I think there are two core parts you need to modify:
One of the core parts is in the [do_query](https://github.com/khiav223577/deep_pluck/blob/v1.1.0/lib/deep_pluck/model.rb#L101) method which is responsible for the `query condition`.
The other is in the [load_data](https://github.com/khiav223577/deep_pluck/blob/v1.1.0/lib/deep_pluck/model.rb#L138) method  where it `plucks attributes` from model.
You may want to take a look at the gem [pluck_all](https://github.com/khiav223577/pluck_all), inspired by this [article](http://meltingice.net/2013/06/11/pluck-multiple-columns-rails/) and used for plucking attributes as hash, first.

And you have to modify the `gemfiles` and `travis.yml` if you want to run test cases with `Mongoid`.
EX:
### .travis.yml
```
env: 
  - DB=mysql
  - DB=pg
```
### 3.2.gemfile
```rb
group :test do
  case ENV['DB']
  when "mysql"    ; gem 'mysql2' , '0.3.21'
  when "postgres" ; gem 'pg', '~> 0.18'
  end
end
```

**Comment by berniechiu** [comment]
cool cool~
let me check check

**Comment by berniechiu** [comment]
While looking at your code, I would like to mark some TODOs first, will be working on it these days maybe ~

### TODO

- [ ] Separate Mongoid/ActiveRecord dependencies (tests too), since only one of them needs to be used https://github.com/kaminari/kaminari/tree/0-17-stable
- [ ] Adapter patterns implementations for different ORM injection, something like this https://www.sitepoint.com/using-and-testing-the-adapter-design-pattern/
