### ISSUE TITLE
Rails 6.1 `map!` deprecation warning

### ISSUE THREAD

**Issue by klausbadelt** [khiav223577/deep_pluck#38]
`DEPRECATION WARNING: map! is deprecated and will be removed from Rails 6.2 (use map instead)` under Rails 6.1 when using `#deep_pluck`. The issue is fixed in [this PR](https://github.com/khiav223577/pluck_all/pull/48) for [pluck_all](https://github.com/khiav223577/pluck_all) - can you merge there? Happy to provide a PR here once a new version of `pluck_all` is published.

**Comment by khiav223577** [comment]
[The PR](https://github.com/khiav223577/pluck_all/pull/48) is merged and new version of pluck_all is released. Looking forward to see a PR for this issue :)
