### ISSUE TITLE
does'nt load translations 

### ISSUE THREAD

**Issue by blazetango** [khiav223577/deep_pluck#49]
I have a class with translations 
 Questionnaire.deep_pluck(:title) returns 

ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column "title" does not exist)
   title is translated field using globalise gem

**Comment by khiav223577** [comment]
It seems that `globalize` override query methods of active_record https://github.com/globalize/globalize/issues/707,
and automatically joins the translation's table.

I'll try and submit a PR to do the same thing when using `deep_pluck` together with `globalize`

**Comment by khiav223577** [comment]
Just release v1.2.0.

See the [CHANGELOG](https://github.com/khiav223577/deep_pluck/blob/master/CHANGELOG.md) for more details
