### ISSUE TITLE
Support for rails 7.0.8

### ISSUE THREAD

**Issue by oztofer** [khiav223577/deep_pluck#62]
I upgraded rails version 7.0.4 to 7.0.8
When I try to use any model with deep_pluck, I get the following:

`.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.0.8/lib/active_record/result.rb:138:in `column_type': wrong number of arguments (given 2, expected 3) (ArgumentError)`

**Comment by khiav223577** [comment]
Thanks for your report. 

I just released v1.3.1 that adds support to rails v7.0.8 ~ v7.1.2.
See the [changelog](https://github.com/khiav223577/deep_pluck/blob/master/CHANGELOG.md) for more details
